---
- name: Pre-flight checklist before installing k8s
  hosts: vm_host
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - name: Check if distribution is supported
      fail: 
        msg: Your distribution is actually unsupported. Supported values are 'Fedora', 'CentOS', 'Ubuntu'
      when: 
        - ansible_distribution != 'CentOS'
        - ansible_distribution != 'Fedora'
        - ansible_distribution != 'Ubuntu'

    - name: Check if target distribution is correct
      fail:
        msg: Target distribution is not supported. Supported values are 'Ubuntu', 'CentOS'
      when:
        - k8s.cluster_os != 'CentOS'
        - k8s.cluster_os != 'Ubuntu'

    - name: Check at least one vm for control plane is defined
      fail:
        msg: At least one control plane should be selected
      when: 
        - k8s.control_plane.vms is not defined or k8s.control_plane.vms <= 0

    - name: Check if master is schedulable in case of clusters composed by control plane VMs
      fail:
        msg: When provisioning a cluster without workers, you need to set k8s.master_schedulable to true in vars.
      when:
        - k8s.worker_nodes.vms is not defined or k8s.worker_nodes.vms <= 0
        - not k8s.master_schedulable 

    - name: Fail fast if rook and less than 3 worker nodes
      fail: 
        msg: In order to use rook, at least three worker nodes must be present
      when:
        - k8s.worker_nodes.vms < 3 
        - rook_ceph.install_rook 

    - name: Fail fast if no container runtime is defined
      fail:
        msg: Select at least container runtime 'docker', 'containerd', 'crio'
      when: 
        - k8s.container_runtime != 'crio'
        - k8s.container_runtime != 'docker'
        - k8s.container_runtime != 'containerd'

    - name: Fail fast if no ingress controller is selected
      fail:
        msg: If you want to install an ingress controller, select one among 'nginx', 'haproxy' or 'contour'
      when:
        - ingress_controller.install_ingress_controller == true
        - ingress_controller.type != 'nginx' and ingress_controller.type != 'haproxy' and ingress_controller.type != 'contour'

    - name: Fail fast if no container plugin selected
      fail:
        msg: Select at least a CNI plugin 'calico' or 'flannel'
      when:
        - k8s.network.cni_plugin != 'calico'
        - k8s.network.cni_plugin != 'flannel'
        - k8s.network.cni_plugin != 'cilium'

    - name: Check if an ingress controller is selected before installing rancher
      fail:
        msg: To install Rancher, install_ingress_controller must be true
      when:
        - rancher.install_rancher
        - ingress_controller.install_ingress_controller == false
