---
- name: Install container runtime
  hosts: k8s_nodes
  become: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks:

    - name: Retrieve the minor version
      ansible.builtin.set_fact:
        kubernetes_version: "{{ k8s.cluster_version.split('.') }}"

    - name: Upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest
      when: k8s.cluster_os == 'CentOS'

    - name: Upgrade all packages
      ansible.builtin.apt:
        name: '*'
        state: latest
      when: k8s.cluster_os == 'Ubuntu'

    - name: Ensure prerequisites are met.
      block:
        - name: Add modules to autostart
          ansible.builtin.blockinfile:
            path: /etc/modules-load.d/k8s.conf
            block: |
              overlay
              br_netfilter
            create: true

        - name: Enable br_netfilter
          community.general.modprobe:
            name: "{{ item }}"
            state: present
          loop:
            - br_netfilter
            - overlay

        - name: Enable sysctl values
          ansible.posix.sysctl:
            name: "{{ item.key }}"
            value: "{{ item.value }}"
            state: present
            reload: yes
            sysctl_set: yes
          loop:
            - key: net.ipv4.ip_forward
              value: 1
            - key: net.bridge.bridge-nf-call-ip6tables
              value: 1
            - key: net.bridge.bridge-nf-call-iptables
              value: 1

        - name: Fix dead traffic on Systemd 245+ for cilium
          block:
          - name: Setup sysctl
            ansible.builtin.copy:
              dest: /etc/sysctl.d/99-restore-cilium-traffic.conf
              content: "net.ipv4.conf.lxc*.rp_filter = 0"        

          - name: Ensure sysctl is restarted
            ansible.builtin.service:
              name: systemd-sysctl
              state: restarted
          when:
            - kubernetes_version.1 | int >= 20
            - k8s.cluster_os == "Ubuntu"
            - k8s.network.cni_plugin == "cilium"

    - name: Configure docker on a Ubuntu machine
      block: 
        - name: Ensure required packages are present
          ansible.builtin.apt:
            name:
              - apt-transport-https
              - ca-certificates 
              - gnupg2
              - curl 
              - software-properties-common 
            state: latest

        - name: Add docker repo key
          ansible.builtin.apt_key:
            url: "{{ docker.ubuntu.docker_repo_key }}"
            keyring: "{{ docker.ubuntu.docker_repo_key_file }}"

            state: present

        - name: Ensure the presence of apt-repo for docker
          ansible.builtin.apt_repository:
            repo: "{{ docker.ubuntu.docker_repo }}"
            state: present
            
        - name: Ensure docker packages are installed
          ansible.builtin.apt:
            name: "{{ docker.ubuntu.docker_packages }}"
            state: present

      when: 
        - k8s.container_runtime == 'docker'
        - k8s.cluster_os == 'Ubuntu'

    - name: Configure docker on a CentOS machine
      block: 
        - name: Ensure required packages are present
          ansible.builtin.yum:
            name:
              - yum-utils 
              - device-mapper-persistent-data 
              - lvm2
            state: latest

        - name: Add docker repository
          ansible.builtin.get_url:
            url: "{{ docker.centos.docker_repo }}"
            dest: "/etc/yum.repos.d/docker-ce.repo"

        - name: Ensure docker is installed
          ansible.builtin.yum:
            name: "{{ docker.centos.docker_packages }}"
            state: latest

      when: 
        - k8s.container_runtime == 'docker' 
        - k8s.cluster_os == 'CentOS'

    - name: Ensure docker service is configured
      block:
      - name: Create /etc/docker
        ansible.builtin.file:
          state: directory
          path: /etc/docker
      
      - name: Copy docker configuration in /etc/docker
        ansible.builtin.copy:
          src: files/daemon.json
          dest: /etc/docker/

      - name: Create systemd folder for Docker service
        ansible.builtin.file:
          path: /etc/systemd/system/docker.service.d
          state: directory

      - name: Force systemd to reread configs
        ansible.builtin.systemd:
          daemon_reload: yes

      - name: Ensure docker is enabled and started
        ansible.builtin.systemd: 
          name: docker
          state: restarted
          enabled: true
      when: k8s.container_runtime == 'docker'

    - name: Install cri-o
      block:
        - name: Add crio repo key
          ansible.builtin.apt_key:
            url: "{{ item.key }}"
            keyring: "{{ item.keyring }}"
            state: present
          loop:
            - key: "{{ crio.ubuntu.libcontainers_key }}"
              keyring: "{{ crio.ubuntu.libcontainers_keyring }}"
            - key: "{{ crio.ubuntu.crio_key }}"
              keyring: "{{ crio.ubuntu.crio_keyring }}"
          when: k8s.cluster_os == 'Ubuntu'

        - name: Ensure the presence of apt-repo for cri-o
          ansible.builtin.apt_repository:
            repo: "{{ item.repo }}"
            filename: "{{ item.file }}"
            state: present
          loop: 
            - repo: "{{ crio.ubuntu.libcontainers_repo }}"
              file: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
            - repo: "{{ crio.ubuntu.crio_repo }}"
              file: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{ k8s.cluster_version }}.list

        - name: Temporary fix for memory swap slices on 20.04
          ansible.builtin.lineinfile: 
            path: /etc/default/grub
            regexp: '^GRUB_CMDLINE_LINUX'
            line: 'GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
        
          when: k8s.cluster_os == 'Ubuntu'

        - name: Add kubic CentOS repository
          ansible.builtin.get_url:
            url: "{{ item.url }}"
            dest: "{{ item.file }}"
            validate_certs: false
          loop:
            - file: "/etc/yum.repos.d/devel:kubic:libcontainers:stable.repo"
              url: "{{ crio.centos.libcontainers_repo }}"
            - file: "/etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o.repo"
              url: "{{ crio.centos.crio_repo }}"
          when: k8s.cluster_os == 'CentOS'

        - name: Ensure cri-o is installed - CentOS
          ansible.builtin.yum:
            name: cri-o
            state: latest
          when: k8s.cluster_os == 'CentOS'

        - name: Ensure cri-o is installed - Ubuntu
          ansible.builtin.apt:
            name: 
              - cri-o
              - cri-o-runc
            state: latest
          when: 
            - k8s.cluster_os == 'Ubuntu'
            - kubernetes_version.1 | int <= 20

        - name: Ensure cri-o is installed - Ubuntu
          ansible.builtin.apt:
            name:
              - cri-o
              - crun
            state: latest
          when: 
            - k8s.cluster_os == 'Ubuntu'
            - kubernetes_version.1 | int > 20

        - name: Fire crio-conf template 
          ansible.builtin.template: 
            src: templates/crio.conf.j2
            dest: /etc/crio/crio.conf

        - name: Fire crio-conf template
          ansible.builtin.template:
            src: templates/crio.conf.crun.j2
            dest: /etc/crio/crio.conf.d/01-crio-runc.conf
          when:
            - k8s.cluster_os == 'Ubuntu'
            - kubernetes_version.1 | int > 20

        - name: Remove example CNI configs
          ansible.builtin.file:
            path: "/etc/cni/net.d/{{ item }}"
            state: absent
          loop:
            - 100-crio-bridge.conf
            - 200-loopback.conf

        - name: Force systemd to reread configs
          ansible.builtin.systemd:
            daemon_reload: yes

        - name: Ensure cri-o is enabled and started
          ansible.builtin.systemd:
            name: crio
            state: started
            enabled: true
      when: k8s.container_runtime == 'crio'

    - name: Ensure containerd is configured and installed on CentOS machine
      block:
        - name: Ensure required packages are present
          ansible.builtin.yum:
            name:
              - yum-utils
              - device-mapper-persistent-data
              - lvm2
            state: latest

        - name: Add containerd repository
          ansible.builtin.get_url:
            url: "{{ containerd.containerd_repo }}"
            dest: "/etc/yum.repos.d/docker-ce.repo"

        - name: Ensure containerd is installed
          ansible.builtin.yum:
            name: containerd.io
            state: latest
      when: 
        - k8s.container_runtime == 'containerd'
        - k8s.cluster_os == 'CentOS'

    - name: Ensure containerd is configured and installed on Ubuntu machine
      ansible.builtin.apt:
        name: containerd
        state: latest
      when: 
        - k8s.container_runtime == 'containerd'
        - k8s.cluster_os == 'Ubuntu'

    - name: Ensure containerd service is configured
      block:
        - name: Create /etc/containers
          ansible.builtin.file:
            state: directory
            path: /etc/containerd

        - name: Initialize config
          ansible.builtin.shell: containerd config default > /etc/containerd/config.toml

        - name: Force systemd to reread configs
          ansible.builtin.systemd:
            daemon_reload: yes

        - name: Ensure containerd is enabled and started
          ansible.builtin.systemd:
            name: containerd
            state: restarted
            enabled: true
      when: k8s.container_runtime == 'containerd'

    - name: Reboot nodes before proceeding
      ansible.builtin.reboot:
