---
- name: Prepare kubeadm-config for cluster setup
  hosts: masters[0]
  become: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - name: Set fact for k8s version
      ansible.builtin.set_fact:
        kubernetes_version: v{{ k8s.cluster_version }}.{{ '13' if k8s.cluster_version is version('1.30', '==') else '9' if k8s.cluster_version is version('1.31', '==') else '5' if k8s.cluster_version is version('1.32', '==') else '1' if k8s.cluster_version is version('1.33', '==') }}

    - name: Process installation if cluster is not set
      when: k8s_installed is not defined
      block:
        - name: Generate cluster token # noqa no-changed-when
          ansible.builtin.command: kubeadm token generate
          register: kubetoken_generated

        - name: Set generated token as fact
          ansible.builtin.set_fact:
            kubetoken: "{{ kubetoken_generated.stdout }}"

        - name: Generate certificate key # noqa no-changed-when
          ansible.builtin.command: kubeadm certs certificate-key
          register: kubecert_generated

        - name: Set generated token as fact
          ansible.builtin.set_fact:
            kubecertkey: "{{ kubecert_generated.stdout }}"

        - name: Add kubelet config for node
          ansible.builtin.template:
            src: templates/kubeadm-config.yaml.j2
            dest: /tmp/kubeadm-config.yaml
            mode: "0755"
