--- 
- name: Prepare cluster to install rook
  hosts: vm_host
  run_once: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - name: Take all required steps to install Rook in your cluster
      block:
        - name: Ensure the needed Namespaces exist.
          kubernetes.core.k8s:
            definition:
              api_version: v1
              kind: Namespace
              metadata:
                name: rook-ceph
            kubeconfig: "clusters/{{ k8s.cluster_name }}/admin.kubeconfig"
            state: present

        - name: Add helm chart repository for Rook
          kubernetes.core.helm_repository:
            name: "{{ item.name }}"
            repo_url: "{{ item.repo_url }}"
          loop:
            - name: "{{ rook.operator.chart.name }}"
              repo_url: "{{ rook.operator.chart.url }}"
            - name: "{{ rook.cluster.chart.name }}"
              repo_url: "{{ rook.cluster.chart.url }}"

        - name: Ensure rook-operator helm chart is installed
          kubernetes.core.helm:
            name: rook-operator
            chart_ref: "{{ rook.operator.chart.ref }}"
            kubeconfig: "clusters/{{ k8s.cluster_name }}/admin.kubeconfig"
            release_namespace: rook-ceph
            update_repo_cache: true
            values:
              csi:
                provisionerReplicas: "{{ rook_ceph.rook_cluster_size }}"
            wait: true

        - name: Trigger rook template
          template:
            src: templates/rook-values.yml.j2
            dest: /tmp/{{ k8s.cluster_name }}/rook-values.yaml

        - name: Ensure rook-ceph-cluster helm chart is installed
          kubernetes.core.helm:
            name: rook-ceph-cluster
            chart_ref: "{{ rook.cluster.chart.ref }}"
            kubeconfig: "clusters/{{ k8s.cluster_name }}/admin.kubeconfig"
            release_namespace: rook-ceph
            update_repo_cache: true
            values_files:
              - /tmp/{{ k8s.cluster_name }}/rook-values.yaml
            wait: true
      when: rook_ceph.install_rook
