rm -rf /etc/NetworkManager/dnsmasq.d/k8s-prod-libvirt_dnsmasq.conf
rm -rf /etc/NetworkManager/conf.d/k8s-prod-localdns.conf
virsh destroy k8s-prod-worker-2
virsh destroy k8s-prod-worker-1
virsh destroy k8s-prod-worker-0
virsh destroy k8s-prod-master-0
virsh destroy k8s-prod-loadbalancer
virsh undefine k8s-prod-loadbalancer
virsh undefine k8s-prod-worker-2
virsh undefine k8s-prod-worker-1
virsh undefine k8s-prod-worker-0
virsh undefine k8s-prod-master-0
virsh net-destroy k8s-prod
virsh net-undefine k8s-prod
virsh pool-destroy k8s-prod
virsh pool-undefine k8s-prod
rm -rf clusters/
rm -rf /var/lib/libvirt/images/k8s-prod/
