collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: ansible.utils
    version: ">=2.10.0"
  - name: community.crypto
    version: ">=2.15.0"
  - name: community.general
    version: ">=7.0.0"
  - name: kubernetes.core
    version: ">=2.4.0"
